server:
  port: ${application.server.port}
spring:
  profiles:
    active:
      - hibernate
      - security
      - spring-cloud
      - ${application.vendor.concurrency-tracker}
      - ${application.vendor.database}
      - ${application.vendor.messaging}

application:
  name: drive-api
  server:
    port: ${SERVER_PORT:8080}
  messaging:
    private:
      consumer:
        file-created:
          concurrency: ${PRIVATE_CONSUMER_FILE_CREATED_CONCURRENCY:1}
          max-attempts: ${PRIVATE_CONSUMER_FILE_CREATED_MAX_ATTEMPTS:5}
        acl-direct-entry-granted:
          concurrency: ${PRIVATE_CONSUMER_ACL_DIRECT_ENTRY_GRANTED_CONCURRENCY:1}
          max-attempts: ${PRIVATE_CONSUMER_ACL_DIRECT_ENTRY_GRANTED_MAX_ATTEMPTS:5}
  outbox:
    relay:
      fixed-rate: ${OUTBOX_RELAY_FIXED_RATE:60000}
  vendor:
    concurrency-tracker: ${VENDOR_CONCURRENCY_TRACKER:inmemory}
    database: ${VENDOR_DATABASE:postgres}
    messaging: ${VENDOR_MESSAGING:rabbitmq}
